language: python
python:
  - "3.6"
  - "3.9"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements/requirements-test.txt
script: pytest tests -x -vv
branches:
  only:
    - dev
    - master