language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
os:
  - linux
install:
  - pip install .
  - pip install -r requirements/requirements-test.txt
script: pytest --remote-data --cov=henge
branches:
  only:
    - dev
    - master