site_name: Henge
site_url: http://henge.databio.org/
repo_url: http://github.com/databio/henge
pypi_name: henge

nav:
  - Getting Started: 
    - Introduction: README.md
  - How-to Guides:
    - "Tutorial": tutorial.md
    - Persisting data: persisting_data.md
  - Reference:
    - Support: https://github.com/databio/henge/issues
    - Changelog: changelog.md
    - API: autodoc_build/henge.md
theme: databio

plugins:
  - databio:
      autodoc_package: "henge"
      autodoc_build: "docs/autodoc_build"
      no_top_level: true
  - search
